### ISSUE TITLE
How to have a quick start?

### ISSUE THREAD

**Issue by Marverlises** [bryanoliveira/soccer-twos-env#5]
I think your work is so wonderful. I'm also carrying out research on reinforcement learning. But I want to ask you how to do a quick start on this project. Because I not familiar with Unity. I already download your unity env but when I start the project it always shows
![image](https://user-images.githubusercontent.com/96861449/202895452-9f748b5b-a690-46c0-af86-0aa3d65c17fe.png)

![image](https://user-images.githubusercontent.com/96861449/202895447-7d1d0194-a253-403a-bff0-417687664437.png)
Could you give me a quick start demo. If possible, can we add a contact ？Thank you sincerely in advance.

**Comment by bryanoliveira** [comment]
Hi! Thanks for using this project. It seems like your PC isn't able download the compiled env [from Google Drive](https://github.com/bryanoliveira/soccer-twos-env/blob/main/soccer_twos/package.py#L46) (maybe due to a VPN or regional block?). I uploaded the binaries in the latest release [here](https://github.com/bryanoliveira/soccer-twos-env/releases/tag/0.1.13), so you should be able to extract e.g. `windows-x86_64.zip` to `<PACKAGE INSTALL LOCATION>/bin/v2/` and run the environment normally.

**Comment by Marverlises** [comment]
I sincerely thank you for your reply and the relevant information you have taken the time to provide, and I will try again.😃
